import React from 'react'
import { createRoot } from 'react-dom/client'
import { Play, Pause, Upload, Settings2, Music2, Hand, Languages, RotateCcw, BookOpen, Image as ImageIcon } from 'lucide-react'
import './styles.css'
import { mushafStyles, defaultMushafStyle, type MushafStyleId } from './mushafStyles'
import { seedQuran } from './quranData'
import { surahCatalog } from './surahCatalog'
import { LiveMushafPreview } from './LiveMushafPreview'
import { createTranslationSelection, findTranslation, type TranslationLanguage, type TranslationEntry } from './translationUiModel'
import { createUploadedBackground, type BackgroundMedia } from './backgroundMedia'
import { createAppRuntime } from './appRuntime'
import type { ExportPanelOptions } from './exportPanel'

const highlightColors={gold:'#d9bd63',green:'#9bcf8a',yellow:'#f0dc55',amber:'#e5a84b'}
type TranslationChoice='none'|TranslationLanguage|'en+ur'|'en+ur+ar'
type TranslationRow={surah?:unknown;ayah?:unknown;chapter?:unknown;verse?:unknown;text?:unknown;translation?:unknown}
function App(){
 const [surahNumber,setSurahNumber]=React.useState(1),[mushafStyle,setMushafStyle]=React.useState<MushafStyleId>(defaultMushafStyle),[highlight,setHighlight]=React.useState<keyof typeof highlightColors>('gold'),[speed,setSpeed]=React.useState(50),[translation,setTranslation]=React.useState<TranslationChoice>('en'),[playing,setPlaying]=React.useState(false),[time,setTime]=React.useState(0),[pageUrl,setPageUrl]=React.useState<string|null>(null),[audioUrl,setAudioUrl]=React.useState<string|null>(null),[audioName,setAudioName]=React.useState('Demo timing'),[translationName,setTranslationName]=React.useState('Built-in demo translation'),[customTranslations,setCustomTranslations]=React.useState<TranslationEntry[]>([]),[page,setPage]=React.useState(1),[token,setToken]=React.useState(()=>localStorage.getItem('qvm_qf_token')||''),[clientId,setClientId]=React.useState(()=>localStorage.getItem('qvm_qf_client')||''),[settingsOpen,setSettingsOpen]=React.useState(false),[status,setStatus]=React.useState('Development data'),[showFinger,setShowFinger]=React.useState(true),[autoScroll,setAutoScroll]=React.useState(true),[showHighlight,setShowHighlight]=React.useState(true),[background,setBackground]=React.useState<BackgroundMedia|null>(null),[backgroundFit,setBackgroundFit]=React.useState<'cover'|'contain'|'fill'>('cover'),[backgroundOpacity,setBackgroundOpacity]=React.useState(35),[backgroundX,setBackgroundX]=React.useState(50),[backgroundY,setBackgroundY]=React.useState(50),[logoUrl,setLogoUrl]=React.useState<string|null>(null),[logoName,setLogoName]=React.useState('Channel logo'),[logoSize,setLogoSize]=React.useState(18),[logoOpacity,setLogoOpacity]=React.useState(100),[logoX,setLogoX]=React.useState(88),[logoY,setLogoY]=React.useState(90),[exporting,setExporting]=React.useState(false),[exportProgress,setExportProgress]=React.useState(0),[exportUrl,setExportUrl]=React.useState<string|null>(null)
 const selectedSurah=surahCatalog.find(s=>s.number===surahNumber)!,isDemoSurah=surahNumber===1
 const audioRef=React.useRef<HTMLAudioElement>(null),exportCanvasRef=React.useRef<HTMLCanvasElement>(null),runtimeRef=React.useRef(createAppRuntime()),duration=15.7
 const activeIndex=isDemoSurah?seedQuran.findIndex(a=>time>=a.words[0].start&&time<a.words[a.words.length-1].end):-1
 const activeAyah=activeIndex>=0?seedQuran[activeIndex]:seedQuran[0],activeWordIndex=Math.max(0,activeAyah.words.findIndex(w=>time>=w.start&&time<w.end)),style=mushafStyles.find(s=>s.id===mushafStyle)!,activeVerse=isDemoSurah&&activeIndex>=0?activeAyah.verseKey:undefined,activeAyahNumber=activeIndex>=0?activeIndex+1:1
 React.useEffect(()=>()=>runtimeRef.current.destroy(),[])
 React.useEffect(()=>{runtimeRef.current.setMedia({canvas:exportCanvasRef.current!,audio:audioRef.current});return runtimeRef.current.subscribe(state=>{setExporting(state.status==='recording');setExportProgress(state.progress);if(state.blobUrl)setExportUrl(state.blobUrl);if(state.status==='error')setStatus(state.error||'Export failed')})},[])
 React.useEffect(()=>{if(!playing||audioUrl)return;const id=window.setInterval(()=>setTime(t=>{const n=t+.03;if(n>=duration){setPlaying(false);return duration}return n}),30);return()=>window.clearInterval(id)},[playing,audioUrl])
 React.useEffect(()=>{if(!audioRef.current)return;const audio=audioRef.current;if(playing&&audio.paused)void audio.play();if(!playing&&!audio.paused)audio.pause()},[playing,audioUrl])
 const handleFile=(e:React.ChangeEvent<HTMLInputElement>,cb:(file:File,url:string)=>void)=>{const f=e.target.files?.[0];if(f)cb(f,URL.createObjectURL(f))}
 const parseTranslationFile=async(f:File)=>{try{const raw=await f.text(),data:unknown=JSON.parse(raw),rows:TranslationRow[]=Array.isArray(data)?data as TranslationRow[]:(typeof data==='object'&&data!==null&&'entries' in data&&Array.isArray(data.entries)?data.entries as TranslationRow[]:typeof data==='object'&&data!==null?Object.entries(data).map(([key,text])=>{const [surah,ayah]=key.split(':').map(Number);return {surah,ayah,text}}):[]);const entries:TranslationEntry[]=rows.map(x=>({surah:Number(x.surah??x.chapter),ayah:Number(x.ayah??x.verse),text:String(x.text??x.translation??'')})).filter(x=>x.surah>0&&x.ayah>0&&Boolean(x.text));setCustomTranslations(entries);setTranslationName(f.name);setStatus(`Translation loaded: ${f.name}`)}catch{setStatus('Invalid translation JSON')}}
 const togglePlay=()=>{setPlaying(v=>!v)},reset=()=>{setPlaying(false);setTime(0);audioRef.current?.pause()}
 const saveApiSettings=()=>{localStorage.setItem('qvm_qf_token',token);localStorage.setItem('qvm_qf_client',clientId);setSettingsOpen(false);setStatus(token&&clientId?'API credentials saved locally':'Development data')}
 const selectedLanguages:TranslationLanguage[]=translation==='en+ur'?['en','ur']:translation==='en+ur+ar'?['en','ur','ar']:translation==='none'?[]:[translation]
 const customForActive=(lang:TranslationLanguage)=>findTranslation(createTranslationSelection(lang,customTranslations),surahNumber,activeAyahNumber)
 const exportTranslations=selectedLanguages.map(lang=>{const text=customForActive(lang)?.text||activeAyah.translations?.[lang];return text?{language:lang,text}:null}).filter(Boolean) as {language:string;text:string}[]
 const handleBackground=(f:File,url:string)=>{const uploaded=createUploadedBackground(f);setBackground({...uploaded,url,kind:f.type.startsWith('video/')?'video':'upload'});setStatus(`Background loaded: ${f.name}`)},handleLogo=(f:File,url:string)=>{setLogoUrl(url);setLogoName(f.name);setStatus(`Logo loaded: ${f.name}`)}
 const startExport=()=>{const opts:ExportPanelOptions={resolution:'1080p',fps:30,mushafStyle,translationLanguage:translation,filename:'quran-video.webm'};runtimeRef.current.startExport(opts);setStatus('Exporting video…')}
 return <div className="app-shell">{audioUrl&&<audio ref={audioRef} src={audioUrl} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onLoadedMetadata={e=>setStatus(`Audio loaded · ${formatTime(e.currentTarget.duration)}`)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} />}
 <header className="topbar"><div><div className="brand">Quran Video Maker</div><div className="subtitle">Quran recitation video studio · synchronized preview</div></div><div className="top-actions"><button className="ghost" onClick={()=>setSettingsOpen(v=>!v)}><Settings2 size={16}/> Settings</button><button className="primary" onClick={togglePlay}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Preview'}</button></div></header>
 {settingsOpen&&<div className="settings-pop"><strong>Quran Foundation API</strong><small>Credentials are stored only in this browser. Never commit secrets to GitHub.</small><input type="password" placeholder="Access token" value={token} onChange={e=>setToken(e.target.value)}/><input type="text" placeholder="Client ID" value={clientId} onChange={e=>setClientId(e.target.value)}/><button className="primary" onClick={saveApiSettings}>Save locally</button></div>}
 <main className="workspace"><aside className="sidebar left-panel"><section className="panel-section"><div className="section-title"><BookOpen size={16}/> Quran</div><label>Surah</label><select value={surahNumber} onChange={e=>{setSurahNumber(Number(e.target.value));setPlaying(false);setTime(0)}}>{surahCatalog.map(s=><option key={s.number} value={s.number}>{s.number}. {s.name} — {s.arabic}</option>)}</select><small className="hint">{selectedSurah.ayahs} ayahs · Surah {selectedSurah.number}</small><label>Mushaf style</label><select value={mushafStyle} onChange={e=>{setMushafStyle(e.target.value as MushafStyleId);setPage(1)}}>{mushafStyles.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><small className="hint">{style.description}</small><label>Page</label><input type="number" min="1" value={page} onChange={e=>setPage(Math.max(1,Number(e.target.value)||1))}/><label className="upload-box"><Upload size={18}/><span>{pageUrl?'Quran page loaded':'Upload Quran page'}</span><small>PNG, JPG, WEBP</small><input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)setPageUrl(URL.createObjectURL(f))}}/></label></section>
 <section className="panel-section"><div className="section-title"><Music2 size={16}/> Audio</div><label className="upload-box"><span>{audioName}</span><small>MP3, WAV, M4A</small><input hidden type="file" accept="audio/*" onChange={e=>handleFile(e,(f,u)=>{setAudioUrl(u);setAudioName(f.name);setStatus(`Audio loaded: ${f.name}`)})}/></label><label>Speed</label><input type="range" min="25" max="100" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></section>
 <section className="panel-section"><div className="section-title"><Hand size={16}/> Highlight</div><label>Highlight color</label><div className="swatches">{(Object.keys(highlightColors) as (keyof typeof highlightColors)[]).map(k=><button key={k} className={`swatch ${highlight===k?'active':''}`} style={{background:highlightColors[k]}} onClick={()=>setHighlight(k)}>{k}</button>)}</div><label className="check"><input type="checkbox" checked={showHighlight} onChange={e=>setShowHighlight(e.target.checked)}/> Highlight active line and word</label><label className="check"><input type="checkbox" checked={showFinger} onChange={e=>setShowFinger(e.target.checked)}/> Show reading finger</label><label className="check"><input type="checkbox" checked={autoScroll} onChange={e=>setAutoScroll(e.target.checked)}/> Auto-scroll with recitation</label></section>
 <section className="panel-section"><div className="section-title"><Languages size={16}/> Translation</div><label>Display</label><select value={translation} onChange={e=>setTranslation(e.target.value as TranslationChoice)}><option value="none">Arabic only</option><option value="en">English</option><option value="ur">Urdu</option><option value="ar">Arabic translation</option><option value="en+ur">English + Urdu</option><option value="en+ur+ar">English + Urdu + Arabic</option></select><small className="hint">{translationName}</small><label className="upload-box"><Upload size={18}/><span>Upload translation JSON</span><small>EN / UR / AR · one file</small><input hidden type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void parseTranslationFile(f)}}/></label></section>
 <section className="panel-section"><div className="section-title"><ImageIcon size={16}/> Background</div><label className="upload-box"><span>{background?.name||'Upload background'}</span><small>Image or video</small><input hidden type="file" accept="image/*,video/*" onChange={e=>handleFile(e,handleBackground)}/></label><label>Fit</label><select value={backgroundFit} onChange={e=>setBackgroundFit(e.target.value as 'cover'|'contain'|'fill')}><option value="cover">Cover</option><option value="contain">Contain</option><option value="fill">Fill</option></select><label>Opacity</label><input type="range" min="0" max="100" value={backgroundOpacity} onChange={e=>setBackgroundOpacity(Number(e.target.value)}/><label>Logo</label><label className="upload-box"><span>{logoName}</span><small>PNG / WEBP</small><input hidden type="file" accept="image/png,image/webp,image/jpeg" onChange={e=>handleFile(e,handleLogo)}/></label></section>
 </aside><section className="preview-area"><div className="preview-toolbar"><div><strong>Preview</strong><span>{selectedSurah.name} · {style.label}</span></div><div className="toolbar-actions"><button className="ghost" onClick={reset}><RotateCcw size={15}/> Reset</button><button className="primary" onClick={togglePlay}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'}</button><button className="primary" onClick={startExport} disabled={exporting}>{exporting?`Exporting ${Math.round(exportProgress)}%`:'Export video'}</button>{exportUrl&&<a className="ghost" href={exportUrl} download="quran-video.webm">Download WebM</a>}</div></div><div className="stage"><LiveMushafPreview styleId={mushafStyle} page={page} accessToken={token} clientId={clientId} activeVerse={activeVerse} activeWordIndex={activeWordIndex} highlight={highlightColors[highlight]} showFinger={showFinger} autoScroll={autoScroll} scrollSpeed={speed} onStatus={setStatus} exportCanvasRef={exportCanvasRef} exportBackground={background?{url:background.url,kind:background.kind,opacity:backgroundOpacity/100,fit:backgroundFit,x:backgroundX,y:backgroundY}:undefined} exportLogo={logoUrl?{url:logoUrl,opacity:logoOpacity,size:logoSize,x:logoX,y:logoY}:undefined} exportTranslations={exportTranslations}/></div><div className="timeline"><div className="timecode">{formatTime(time)} / {formatTime(duration)}</div><input type="range" min="0" max={duration} step="0.01" value={time} onChange={e=>setTime(Number(e.target.value))}/></div></section></main><footer className="statusbar"><span>{status}</span><span>Surah {surahNumber} · Ayah {activeAyahNumber}{activeVerse?` · ${activeVerse}`:''}</span></footer></div>
}
function formatTime(seconds:number){if(!Number.isFinite(seconds))return '00:00';const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)