import type { TranslationTrack } from './translationRegistry'
export type TranslationEntry = TranslationTrack
export interface TranslationRecord { surah:number; ayah:number; text:string }
export interface TranslationDataset { version:string; language:'ar'|'en'|'ur'; edition:string; translator?:string; source?:string; license?:string; attribution?:string; records:TranslationRecord[] }
export function validateTranslationDataset(data:unknown):data is TranslationDataset{if(!data||typeof data!=='object')return false;const d=data as Record<string,unknown>;if(typeof d.version!=='string'||!['ar','en','ur'].includes(String(d.language))||typeof d.edition!=='string'||!Array.isArray(d.records))return false;return d.records.every(item=>{if(!item||typeof item!=='object')return false;const r=item as Record<string,unknown>;return typeof r.surah==='number'&&typeof r.ayah==='number'&&typeof r.text==='string'})}
export function parseTranslationDataset(json:string):TranslationDataset{const data:unknown=JSON.parse(json);if(!validateTranslationDataset(data))throw new Error('Invalid translation dataset.');return data}
export async function loadOnlineTranslation(entry:TranslationEntry):Promise<TranslationDataset>{if(!entry.url)throw new Error('Selected translation has no online source URL.');const response=await fetch(entry.url);if(!response.ok)throw new Error(`Unable to load translation (${response.status}).`);const data=parseTranslationDataset(await response.text());if(data.language!==entry.language)throw new Error('Translation language does not match the selected edition.');return data}
export function getTranslationText(dataset:TranslationDataset,surah:number,ayah:number){return dataset.records.find(item=>item.surah===surah&&item.ayah===ayah)?.text??''}
export function parseUploadedTranslation(fileText:string):TranslationDataset{return parseTranslationDataset(fileText)}
